blank_issues_enabled: true
contact_links:
  - name: JG RTX Discord
    url: https://discord.com/channels/846064688491528193/1277229415843237889
    about: Ask questions or discuss features in the plugin author's Discord
